settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: bing
    name: BingAI
    url: 'https://bing.xhustoj.eu.org/'
    method: GET
    expectStatus: 200

  - id: img
    name: 上传图片
    url: 'https://img.luking.top/'
    method: GET
    expectStatus: 200

  - id: pic
    name: 图床
    url: 'https://pic.luking.top/'
    method: GET
    expectStatus: 200

  - id: dlj
    name: 短连接
    url: 'https://dlj.luking.top/'
    method: GET
    expectStatus: 200

  - id: git
    name: github加速
    url: 'https://git.luking.top/'
    method: GET
    expectStatus: 200

  - id: proxy
    name: 反向代理
    url: 'https://proxy.luking.top/'
    method: GET
    expectStatus: 200

  - id: blog-cloudflare-com
    name: The Cloudflare Blog
    url: 'https://status.luking.top/'
    method: GET
    expectStatus: 200
